#########################################################################
# LitePing by xDefcon - Configuration file
# Please check for updates, and remember to update the config if needed!
#########################################################################

# Section related to /ping command.
ping-command:
  # Customize the output of the command, use %ping% to indicate player's latency.
  ping-message: "&a[Ping] &7Your ping is: &a%ping%ms"
  # Customize the output of the command to check the ping of another player (if enabled).
  # Use %target% to indicate the name of the target player, use %ping% to indicate player's latency.
  ping-target-message: "&a[Ping] &7The ping of &a%target% &7is: &a%ping%ms"

# Section related to the per command permission system.
permission-system:
  # Set this to true if you want to enable the permission system.
  enabled: false
  # Customize the message sent to the players if they do not have required permission.
  no-perm-message: "&cYou do not have permissions to execute this command."

# Section related to the /ping <targetPlayer> command
others-ping:
  # Set this to false if you want to DISALLOW users to check the ping of another player.
  show-other-players-ping: true
  # Customize the message sent to the players if they do not have required permission.
  not-allowed-message: "&cYou do not have permission to check the ping of other players."
  # Customize the message sent to the players if the specified player can not be found.
  player-not-found: "&cThe specified player is not online."

# Section related to the tablist management (you can open the tablist by pressing TAB in game).
tablist:
  # Set this to true if you want to show player's ping in the tablist.
  enabled: true
  # Set this to true if you want to display the name of the player WITHOUT colors added by plugins like Essentials.
  # Set to false if you want to show the "display-name" (the name of the player WITH colors added by external plugins).
  show-real-name: true
  # Customize the tablist prefix, use %ping% to indicate player's latency. You do not need to put a space at the end. Set this to "" to disable.
  prefix: "&7[&a%ping%ms&7]"
  # Customize the tablist suffix, use %ping% to indicate player's latency. Set this to "" to disable.
  suffix: ""
  # Update delay time (in seconds) - 5 means that the tablist is updated every 5 seconds.
  update-delay: 5
