name: LitePing
main: me.interrrp.liteping.LitePing
author: interrrp
version: "2.6"
api-version: "1.14"
description: "LitePing - A simple and customizable plugin to show your ping."
commands:
  ping:
    description: Show your/another player's ping.
  pingreload:
    description: Reload the plugin.
